#!/usr/bin/sh

# Iniciar sxhkd
sxhkd &

# start with bspwm 

xrandr --output DisplayPort-0 --off --output HDMI-A-0 --mode 1440x900 --pos 1600x0 --rotate normal --output DVI-D-0 --mode 1600x900 --pos 0x0 --rotate normal

# Ventanas 
bspc config border_width         5
bspc config focused_border_color \#C3BBEC
bspc config normal_border_color \#D9D8E0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# AUTOSTART
picom &
# En caso de dunst no se inicie vamos a la ruta de nuestro servicio de notificaciones 
# en este caso kde : sudo nano /usr/share/dbus-1/services/org.kde.plasma.Notifications.service

#  Agregamos esta linea donde le cambiamos el nombre: Name=org.freedesktop.TestNotifications

# y comentamos la que venia por defecto Name=org.freedesktop.Notifications
pkill dunst &
dunst -c ~/.config/dunst/dunstrc &
feh --bg-scale "/home/dani/Imágenes/Monterey.png" &
$HOME/.config/polybar/launch.sh &
