#!/usr/bin/sh

sxhkd &

bspc monitor DisplayPort-0 -n monitor0 -d I II III
bspc monitor HDMI-A-0 -n monitor1 -d IV
bspc monitor HDMI-A-0 -s DisplayPort-0
bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# AUTOSTART
picom &
ulauncher &
feh --bg-scale "/home/sergio/Fondos/catalina.jpg" &
$HOME/.config/polybar/grayblocks/launch.sh &