#!/usr/bin/sh

#Configs side of monitors BSPWM
SECOND_MONITOR_SIDE="left"


#Get Monitors
PRINCIPAL=$(xrandr | grep primary | awk '{print $1}')
SECOND_MONITOR=$(xrandr | grep connected | awk '{i++}i==2'| awk '{print $1}')
sxhkd &

 Configure Monitors 
if [ "$(xrandr | grep -sw 'connected' | wc -l)" = "2" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d I II III IV V
  bspc monitor $(bspc query -M | sed -n 2p) -d VI VII VIII IX X
  #Set Monitors Side and output 
  xrandr --output $SECOND_MONITOR --$SECOND_MONITOR_SIDE-of $PRINCIPAL  
else
  bspc monitor -d I II III IV V VI VII VIII IX X 
fi


# Ventanas 
bspc config border_width         5
bspc config focused_border_color \#C3BBEC
bspc config normal_border_color \#D9D8E0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# AUTOSTART
picom &
pkill dunst &
dunst -conf ~/.config/dunst/dunstrc &
feh --bg-scale "/home/daniel/Fondos/img19.jpg" &
$HOME/.config/polybar/launch.sh &
